public class ChangelogScreen {
    public static void print() {
        System.out.println("Convert4Free Changelog");
        System.out.println();
        System.out.println("Version 0.5.1");
        System.out.println("- Fixed output file selection in the desktop UI");
        System.out.println("- Rebuilt the installer as a real jar-only installer");
        System.out.println("- Installer now lets you choose where Convert4Free.jar is created");
        System.out.println("- Installer no longer leaves GitHub source code behind");
        System.out.println();
        System.out.println("Version 0.5.0");
        System.out.println("- Added more than 50 converter presets");
        System.out.println("- Added video, audio, web, legacy, animation, and editing outputs");
        System.out.println("- Added quality and audio/video settings");
        System.out.println("- Improved the file-first conversion flow");
        System.out.println("- Simplified the README");
        System.out.println();
        System.out.println("Version 0.4.1");
        System.out.println("- File-first desktop workflow");
        System.out.println("- The app now detects the selected input format");
        System.out.println("- Only possible output formats are shown after choosing a file");
        System.out.println("- Added an embedded HTML/CSS update log page");
        System.out.println("- Reworked the status area with friendlier progress text");
        System.out.println();
        System.out.println("Version 0.4.0");
        System.out.println("- Fully rebuilt the desktop UI");
        System.out.println("- Added native Windows file picker dialogs");
        System.out.println("- Improved the conversion workflow and status area");
        System.out.println();
        System.out.println("Version 0.3.0");
        System.out.println("- Improved MKV to MP4 for After Effects");
        System.out.println("- Converts MKV audio to AAC stereo");
        System.out.println("- Mixes multiple MKV audio tracks into one editing-friendly track");
        System.out.println();
        System.out.println("Version 0.2.0");
        System.out.println("- Added MP4 to MOV conversion");
        System.out.println("- Added MP4 to MP3 audio extraction");
        System.out.println("- Redesigned the desktop UI for multiple conversion modes");
        System.out.println("- Added automatic output extension suggestions");
        System.out.println();
        System.out.println("Version 0.1.0");
        System.out.println("- Added MKV to MP4 conversion");
        System.out.println("- Added audio and video stream preservation using FFmpeg");
        System.out.println("- Added command-line input/output support");
        System.out.println("- Added credits screen");
        System.out.println("- Added changelog screen");
        System.out.println("- Added basic file validation");
        System.out.println("- Added overwrite protection");
        System.out.println("- Added desktop UI");
        System.out.println("- Added GitHub updater");
    }
}
